---
name: Rollout Release Action 

on:
  workflow_call:
    inputs:
      instance_name:
        type: string
        required: true
      instance_stage:
        type: string
        required: true
      frontend_hostname:
        type: string
        required: true
      release_tag:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      KUBECONFIG:
        required: true
      RC_WEBHOOK: 
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ inputs.instance_name }}-rollout-release
  cancel-in-progress: true

jobs:
  rollout:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: 'dBildungsplattform/spsh-app-deploy'
          # ref: "${{ inputs.release_tag }}"
          ref: DBP-681-SPSH-Release-Process

      - name: Install kubectl and Helm
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f #v4.0.0

      - name: Set kubeconfig
        run: |
          mkdir /home/runner/.kube/
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
          chmod 600 /home/runner/.kube/config

      - name: Helm add repo dbilungsplattform
        run: |
          helm repo add dbildungsplattform https://dbildungsplattform.github.io/helm-charts-registry/

      - name: Rollout dbildungs-iam-keycloak Helm Chart 
        run: |
            helm upgrade --install \
            dbildungs-iam-keycloak \
            dbildungsplattform/dbildungs-iam-keycloak \
            --namespace spsh \
            --kubeconfig /home/runner/.kube/config \
            --version ${{ inputs.release_tag }} \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/general/values.yml \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/dbildungs-iam-keycloak/values.yml \
            --wait

      - name: Rollout schulportal-client Helm Chart 
        run: |
            helm upgrade --install \
            schulportal-client \
            dbildungsplattform/schulportal-client \
            --namespace spsh \
            --kubeconfig /home/runner/.kube/config \
            --version ${{ inputs.release_tag }} \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/general/values.yml \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/schulportal-client/values.yml \

      - name: Rollout dbildungs-iam-server Helm Chart 
        run: |
            helm upgrade --install \
            dbildungs-iam-server \
            dbildungsplattform/dbildungs-iam-server \
            --namespace spsh \
            --kubeconfig /home/runner/.kube/config \
            --version ${{ inputs.release_tag }} \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/general/values.yml \
            --values ./config/helm-charts/${{ inputs.instance_stage }}/dbildungs-iam-server/values.yml \

      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Rollout of ${{ inputs.instance_name }} triggered by ${{ github.actor }}:'
          url: ${{ secrets.RC_WEBHOOK }}
          channel: '#SPSH-Release'
          username: Rollout Release Info

  # # A User has to be available and add repo secret USER and PW for this to function
  # tests_playwright:
  #   needs: 
  #     - rollout
  #   uses: dBildungsplattform/schulportal-testautomatisierung/.github/workflows/playwright.yml@1
  #   with:
  #     frontendHostname: ${{ inputs.frontend_hostname }}
  #   secrets: inherit