---
name: Rollout to Instances
run-name: Rollout of ${{ env.release_tag }} to ${{ inputs.target_instances }}

on:
  push:
  workflow_dispatch:
    inputs:
      target_instances:
        description: "Decide where to do the rollout. Choose a Stage, a single instance or everywhere with 'all'. Default: all"
        required: true
        default: all

env: 
  release_tag: 8.8.12

jobs:
  # approve_staging:
  #   environment: approve_staging
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Version of release tag ${{ github.event.inputs.release_tag }}"
  #     - run: echo "Target(s) to rollout to ${{ github.event.inputs.target_instances }}"
  #     - run: echo "Workflow is triggered by ${{ github.ref_type }} ${{ github.ref_name }}"

  spsh-staging-schulportal:
    # needs:
      # - approve_staging
    if:  inputs.target_instances == 'spsh-staging-schulportal' || inputs.target_instances == 'staging' || inputs.target_instances == 'all'
    uses: ./.github/workflows/rollout-release.yml
    with:
      instance_name: spsh-staging-schulportal
      instance_stage: staging
      frontend_hostname: "spsh.staging.spsh.dbildungsplattform.de"
      release_tag: ${{ env.release_tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.SPSH_STAGING_KUBECONFIG }}
      RC_WEBHOOK:  ${{ secrets.RC_WEBHOOK }} 

  # approve_prod:
  #   needs:
  #     - spsh-staging-schulportal
  #   environment: approve_prod
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Version ${{ github.event.inputs.release_tag }}"
  #     - run: echo "Target(s) to rollout to ${{ github.event.inputs.target_instances }}"
  #     - run: echo "Workflow is triggerd by ${{ github.ref_type }} ${{ github.ref_name }}"
     
  # spsh-prod-schulportal:
  #     if:  inputs.target_instances == 'spsh-prod-schulportal' || inputs.target_instances == 'prod' || inputs.target_instances == 'all'
  #     needs:
  #       - approve_prod
  #     uses: ./.github/workflows/rollout-release.yml
  #     with:
  #       instance_name: spsh-prod-schulportal
  #       instance_stage: prod
  #       frontend_hostname: "spsh.prod.spsh.dbildungsplattform.de"
  #       release_tag: ${{ env.release_tag }}
  #     secrets:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       KUBECONFIG: ${{ secrets.SPSH_PROD_KUBECONFIG }}
  #       # RC_WEBHOOK:  ${{ secrets.RC_WEBHOOK }} 
